name: iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test FlipperZero(ios) scheme using iPhone 11 simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode version selection
        run: sudo xcode-select --switch /Applications/Xcode_12.app
      - name: SwiftLint report
        run: swiftlint lint --reporter github-actions-logging --config "FlipperZero/.swiftlint.yml"
      - name: Xcode test
        run: xcodebuild -sdk iphonesimulator -workspace ./FlipperZero/FlipperZero.xcodeproj/project.xcworkspace -scheme 'FlipperZero(iOS)' -derivedDataPath ./output/DerivedData -enableCodeCoverage YES test DSTROOT=./output/test/build.dst OBJROOT=./output/test/build.obj SYMROOT=./output/test/build.sym SHARED_PRECOMPS_DIR=./output/test/build.pch -destination platform='iOS Simulator,name=iPhone 11' | xcpretty
      - name: Code coverage report
        run: xcrun xccov view --report ./output/DerivedData/Logs/Test/*.xcresult
